<a href="https://colab.research.google.com/github/Chandan801/Dr.Proton/blob/master/Numpy%20Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.arange(1000)
%timeit a**2

In [ ]:
a=np.tile(np.arange(0,80,20),(3,1))
print (a)
print("***********")
a=a.T
print(a)

In [ ]:
b=np.array([0,1,2])
a+b

In [ ]:
a=np.arange(0,40,10)
a.shape

(4,)

In [ ]:
a=a[:, np.newaxis] #adds new axis or 2D array
print(a.shape)

(4, 1)


In [ ]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel() #prints 2D array into contiguous array
a.T #Transpose the array
a.reshape(2,3) #reshape the array into it's original form

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.arange(4*3*2).reshape(4,3,2)#4*3*2=24 and it contains 4 matrices which of 3*2
a.shape
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
#Sorting the array
a=np.array([[1,3,2],[5,4,6]])
b=np.sort(a,axis=1)
bm

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=np.array([1,3,4,2])
b=np.argsort(a)#it returns the index value of elements after sorting
a[b]

array([1, 2, 3, 4])